# Generated by Django 5.1.5 on 2025-03-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_semester_minor_sgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='minor_sgpa',
        ),
        migrations.AddField(
            model_name='semester',
            name='minor_cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
