# Generated by Django 5.1.5 on 2025-03-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_remove_semester_minor_sgpa_semester_minor_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='minor_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
