# Generated by Django 5.1.5 on 2025-03-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_semester_minor_sgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='minor_cgpa',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='minor_sgpa',
        ),
    ]
