# Generated by Django 5.1.5 on 2025-03-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_remove_semester_minor_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='minor_cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='minor_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
