# Generated by Django 5.1.5 on 2025-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_semester_minor_cgpa_semester_minor_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='total_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='total_points',
            field=models.FloatField(default=0.0),
        ),
    ]
