# Generated by Django 5.1.5 on 2025-03-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_semester_total_credits_semester_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='earn_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='minor_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='minor_points',
            field=models.FloatField(default=0.0),
        ),
    ]
