# Generated by Django 5.1.5 on 2025-04-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_remove_semester_cgpa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='semester',
            name='minor_cgpa',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='minor_credits',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='minor_gpa',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='minor_points',
        ),
    ]
