# Generated by Django 5.1.5 on 2025-04-01 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_alter_semester_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='minor_cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='minor_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='minor_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='minor_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(default='semester_1', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('user', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('semester', 'name')},
        ),
    ]
