# Generated by Django 5.1.5 on 2025-04-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_semester_minor_cgpa_semester_minor_credits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField()),
                ('grade', models.CharField(choices=[('S', 'S'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('P', 'P'), ('F', 'F')], max_length=2)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_details', to='calculator.subject')),
            ],
        ),
    ]
