
# Credits for each subject (can be moved to a database model if needed)
CREDITS = {
    'CSE': {
        'semester_1': {
            'LINEAR ALGEBRA AND CALCULAS ': 4,
            'ENGINEERING PHYSICS A ': 4,
            'ENGINEERING CHEMISTRY ': 4,
            'ENGINEERING MECHANICS': 3,
            'ENGINEERING GRAPHICS ': 3,
            'BASICS OF CIVIL & MECHANICAL ENGINEERING0 ': 4,
            'BASICS OF ELECTRICAL & ELECTRONICS ENGINEERING ': 4,
            'LIFE SKILLS': 0,
            'ENGINEERING PHYSICS LAB ': 1,
            'CIVIL & MECHANICAL WORKSHOP ':1,
            'ELECTRICAL & ELECTRONICS WORKSHOP':1,
        },
        'semester_2': {
            'VECTORCALCULUS , DIFFERENTIAL EQUATIONS AND TRANSFORMS ': 4,
            'ENGINEERING PHYSICS A ': 4,
            'ENGINEERING CHEMISTRY': 4,
            'ENGINEERING MECHANICS': 3,
            'ENGINEERING GRAPHICS': 3,
            'BASICS OF CIVIL & MECHANICAL ENGINEERING ': 4,
            'BASICS OF ELECTRICAL & ELECTRONICS ENGINEERING ': 4,
            'PROFESSIONAL COMMUNICATION': 0,
            'PROGRAMMING IN C': 4,
            'ENGINEERING PHYSICS LAB': 1,
            'ENGINEERING CHEMISTRY LAB ': 1,
            'CIVIL & MECHANICAL WORKSHOP': 1,
            'ELECTRICAL & ELECTRONICS WORKSHOP': 1,
        },
        'semester_3': {
            'DISCRETE MATHEMATICAL STRUCTURES ': 4,
            'DATA STRUCTURES': 4,
            'LOGIC SYSTEM DESIGN ': 4,
            'OBJECT ORIENTED PROGRAMMING USING JAVA': 4,
            'DESIGN & ENGINEERING': 2,
            'PROFESSIONAL ETHICS ': 2,
            'SUSTAINABLE ENGINEERING ': 0,
            'DATA STRUCTURES LAB ': 2,
            'OBJECT ORIENTED PROGRAMMING LAB (IN JAVA)': 2,
        },
        'semester_4': {
            'GRAPH THEORY': 4,
            'COMPUTER ORGANISATION AND ARCHITECTURE ': 4,
            'DATABASE MANAGEMENT SYSTEMS': 4,
            'OPERATING SYSTEMS': 4,
            'DESIGN & ENGINEERING': 2,
            'PROFESSIONAL ETHICS': 2,
            'CONSTITUTION OF INDIA': 0,
            'DIGITAL LAB ': 2,
            'OPERATING SYSTEMS LAB ': 2,
        },
        'semester_5': {
            'FORMAL LANGUAGES AND AUTOMATA THEORY': 4,
            'COMPUTER NETWORKS': 4,
            'SYSTEM SOFTWARE ': 4,
            'MICROPROCESSORS AND MICROCONTROLLERS ': 4,
            'MANAGEMENT OF SOFTWARE SYSTEMS': 3,
            'DISASTER MANAGEMENT': 0,
            'SYSTEM SOFTWARE AND MICROPROCESSORS LAB ': 2,
            'DATABASE MANAGEMENT SYSTEMS LAB ': 2,
        },
        'semester_6': {
            'COMPILER DESIGN': 4,
            'COMPUTER GRAPHICS AND IMAGE PROCESSING': 4,
            'ALGORITHM ANA LYSIS AND DESIGN': 4,
            'PROGRAM ELECTIVE I ': 3,
            'INDUSTRIAL ECONOMICS & FOREIGN TRADE ': 3,
            'COMPREHENSIVE COURSE WORK ': 1,
            'NETWORKING LAB': 2,
            'MINIPROJECT ':2
        },
    },
    'CE': {
        'semester_1': {
            'ENGINEERING MATHEMATICS I': 4,
            'ENGINEERING PHYSICS': 4,
            'ENGINEERING CHEMISTRY': 4,
            'ENGINEERING MECHANICS': 3,
            'ENGINEERING GRAPHICS': 3,
            'BASICS OF CIVIL ENGINEERING': 4,
            'BASICS OF ELECTRICAL ENGINEERING': 4,
            'LIFE SKILLS': 0,
            'ENGINEERING PHYSICS LAB': 1,
            'CIVIL WORKSHOP': 1,
            'ELECTRICAL WORKSHOP': 1,
        },
        'semester_2': {
            'FORMAL LANGUAGES AND AUTOMATA THEORY': 4,
            'COMPUTER NETWORKS': 4,
            'SYSTEM SOFTWARE ': 4,
            'MICROPROCESSORS AND MICROCONTROLLERS ': 4,
            'MANAGEMENT OF SOFTWARE SYSTEMS': 3,
            'DISASTER MANAGEMENT': 0,
            'SYSTEM SOFTWARE AND MICROPROCESSORS LAB ': 2,
            'DATABASE MANAGEMENT SYSTEMS LAB ': 2,
        },
        'semester_3': {
            'COMPILER DESIGN': 4,
            'COMPUTER GRAPHICS AND IMAGE PROCESSING': 4,
            'ALGORITHM ANA LYSIS AND DESIGN': 4,
            'PROGRAM ELECTIVE I ': 3,
            'INDUSTRIAL ECONOMICS & FOREIGN TRADE ': 3,
            'COMPREHENSIVE COURSE WORK ': 1,
            'NETWORKING LAB': 2,
            'MINIPROJECT ':2
        },
       'semester_4': {
            'GRAPH THEORY': 4,
            'COMPUTER ORGANISATION AND ARCHITECTURE ': 4,
            'DATABASE MANAGEMENT SYSTEMS': 4,
            'OPERATING SYSTEMS': 4,
            'DESIGN & ENGINEERING': 2,
            'PROFESSIONAL ETHICS': 2,
            'CONSTITUTION OF INDIA': 0,
            'DIGITAL LAB ': 2,
            'OPERATING SYSTEMS LAB ': 2,
        },
        'semester_5': {
            'FORMAL LANGUAGES AND AUTOMATA THEORY': 4,
            'COMPUTER NETWORKS': 4,
            'SYSTEM SOFTWARE ': 4,
            'MICROPROCESSORS AND MICROCONTROLLERS ': 4,
            'MANAGEMENT OF SOFTWARE SYSTEMS': 3,
            'DISASTER MANAGEMENT': 0,
            'SYSTEM SOFTWARE AND MICROPROCESSORS LAB ': 2,
            'DATABASE MANAGEMENT SYSTEMS LAB ': 2,
        },
        'semester_6': {
            'COMPILER DESIGN': 4,
            'COMPUTER GRAPHICS AND IMAGE PROCESSING': 4,
            'ALGORITHM ANA LYSIS AND DESIGN': 4,
            'PROGRAM ELECTIVE I ': 3,
            'INDUSTRIAL ECONOMICS & FOREIGN TRADE ': 3,
            'COMPREHENSIVE COURSE WORK ': 1,
            'NETWORKING LAB': 2,
            'MINIPROJECT ':2
        },
    },
    'ME': {
        'semester_1': {
            'ENGINEERING MATHEMATICS I': 4,
            'ENGINEERING PHYSICS': 4,
            'ENGINEERING CHEMISTRY': 4,
            'ENGINEERING MECHANICS': 3,
            'ENGINEERING GRAPHICS': 3,
            'BASICS OF CIVIL ENGINEERING': 4,
            'BASICS OF ELECTRICAL ENGINEERING': 4,
            'LIFE SKILLS': 0,
            'ENGINEERING PHYSICS LAB': 1,
            'CIVIL WORKSHOP': 1,
            'ELECTRICAL WORKSHOP': 1,
        },
        'semester_2': {
            'FORMAL LANGUAGES AND AUTOMATA THEORY': 4,
            'COMPUTER NETWORKS': 4,
            'SYSTEM SOFTWARE ': 4,
            'MICROPROCESSORS AND MICROCONTROLLERS ': 4,
            'MANAGEMENT OF SOFTWARE SYSTEMS': 3,
            'DISASTER MANAGEMENT': 0,
            'SYSTEM SOFTWARE AND MICROPROCESSORS LAB ': 2,
            'DATABASE MANAGEMENT SYSTEMS LAB ': 2,
        },
        'semester_3': {
            'COMPILER DESIGN': 4,
            'COMPUTER GRAPHICS AND IMAGE PROCESSING': 4,
            'ALGORITHM ANA LYSIS AND DESIGN': 4,
            'PROGRAM ELECTIVE I ': 3,
            'INDUSTRIAL ECONOMICS & FOREIGN TRADE ': 3,
            'COMPREHENSIVE COURSE WORK ': 1,
            'NETWORKING LAB': 2,
            'MINIPROJECT ':2
        },
       'semester_4': {
            'GRAPH THEORY': 4,
            'COMPUTER ORGANISATION AND ARCHITECTURE ': 4,
            'DATABASE MANAGEMENT SYSTEMS': 4,
            'OPERATING SYSTEMS': 4,
            'DESIGN & ENGINEERING': 2,
            'PROFESSIONAL ETHICS': 2,
            'CONSTITUTION OF INDIA': 0,
            'DIGITAL LAB ': 2,
            'OPERATING SYSTEMS LAB ': 2,
        },
        'semester_5': {
            'FORMAL LANGUAGES AND AUTOMATA THEORY': 4,
            'COMPUTER NETWORKS': 4,
            'SYSTEM SOFTWARE ': 4,
            'MICROPROCESSORS AND MICROCONTROLLERS ': 4,
            'MANAGEMENT OF SOFTWARE SYSTEMS': 3,
            'DISASTER MANAGEMENT': 0,
            'SYSTEM SOFTWARE AND MICROPROCESSORS LAB ': 2,
            'DATABASE MANAGEMENT SYSTEMS LAB ': 2,
        },
        'semester_6': {
            'COMPILER DESIGN': 4,
            'COMPUTER GRAPHICS AND IMAGE PROCESSING': 4,
            'ALGORITHM ANA LYSIS AND DESIGN': 4,
            'PROGRAM ELECTIVE I ': 3,
            'INDUSTRIAL ECONOMICS & FOREIGN TRADE ': 3,
            'COMPREHENSIVE COURSE WORK ': 1,
            'NETWORKING LAB': 2,
            'MINIPROJECT ':2
        }
    },
    'EEE': {
        'semester_1': {
            'ENGINEERING MATHEMATICS I': 4,
            'ENGINEERING PHYSICS': 4,
            'ENGINEERING CHEMISTRY': 4,
            'ENGINEERING MECHANICS': 3,
            'ENGINEERING GRAPHICS': 3,
            'BASICS OF CIVIL ENGINEERING': 4,
            'BASICS OF ELECTRICAL ENGINEERING': 4,
            'LIFE SKILLS': 0,
            'ENGINEERING PHYSICS LAB': 1,
            'CIVIL WORKSHOP': 1,
            'ELECTRICAL WORKSHOP': 1,
        },
        'semester_2': {
            'FORMAL LANGUAGES AND AUTOMATA THEORY': 4,
            'COMPUTER NETWORKS': 4,
            'SYSTEM SOFTWARE ': 4,
            'MICROPROCESSORS AND MICROCONTROLLERS ': 4,
            'MANAGEMENT OF SOFTWARE SYSTEMS': 3,
            'DISASTER MANAGEMENT': 0,
            'SYSTEM SOFTWARE AND MICROPROCESSORS LAB ': 2,
            'DATABASE MANAGEMENT SYSTEMS LAB ': 2,
        },
        'semester_3': {
            'COMPILER DESIGN': 4,
            'COMPUTER GRAPHICS AND IMAGE PROCESSING': 4,
            'ALGORITHM ANA LYSIS AND DESIGN': 4,
            'PROGRAM ELECTIVE I ': 3,
            'INDUSTRIAL ECONOMICS & FOREIGN TRADE ': 3,
            'COMPREHENSIVE COURSE WORK ': 1,
            'NETWORKING LAB': 2,
            'MINIPROJECT ':2
        },
       'semester_4': {
            'GRAPH THEORY': 4,
            'COMPUTER ORGANISATION AND ARCHITECTURE ': 4,
            'DATABASE MANAGEMENT SYSTEMS': 4,
            'OPERATING SYSTEMS': 4,
            'DESIGN & ENGINEERING': 2,
            'PROFESSIONAL ETHICS': 2,
            'CONSTITUTION OF INDIA': 0,
            'DIGITAL LAB ': 2,
            'OPERATING SYSTEMS LAB ': 2,
        },
        'semester_5': {
            'FORMAL LANGUAGES AND AUTOMATA THEORY': 4,
            'COMPUTER NETWORKS': 4,
            'SYSTEM SOFTWARE ': 4,
            'MICROPROCESSORS AND MICROCONTROLLERS ': 4,
            'MANAGEMENT OF SOFTWARE SYSTEMS': 3,
            'DISASTER MANAGEMENT': 0,
            'SYSTEM SOFTWARE AND MICROPROCESSORS LAB ': 2,
            'DATABASE MANAGEMENT SYSTEMS LAB ': 2,
        },
        'semester_6': {
            'COMPILER DESIGN': 4,
            'COMPUTER GRAPHICS AND IMAGE PROCESSING': 4,
            'ALGORITHM ANA LYSIS AND DESIGN': 4,
            'PROGRAM ELECTIVE I ': 3,
            'INDUSTRIAL ECONOMICS & FOREIGN TRADE ': 3,
            'COMPREHENSIVE COURSE WORK ': 1,
            'NETWORKING LAB': 2,
            'MINIPROJECT ':2
        }
    },
}
