# Generated by Django 5.1.5 on 2025-02-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_ktuid_remove_customuser_is_honors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='KTUID',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_honors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
