# Generated by Django 5.1.5 on 2025-03-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_degree_customuser_targeted_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
