# Generated by Django 5.1.5 on 2025-04-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_faculty_username_alter_faculty_college_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='college_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
