# Generated by Django 5.1.5 on 2025-04-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_college_code_customuser_is_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='college_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
