# Generated by Django 5.1.5 on 2025-04-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_is_verified_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
